### ISSUE TITLE
sscache is outdated

### ISSUE THREAD

**Issue by aminya** [AnotherFoxGuy/choco-pkg#2]
The latest version is 0.2.13
https://github.com/mozilla/sccache/releases

**Comment by AnotherFoxGuy** [comment]
I'm aware of it, I haven't updated because of this issue: https://github.com/mozilla/sccache/issues/677

**Comment by AnotherFoxGuy** [comment]
Fixed in commit https://github.com/AnotherFoxGuy/choco-pkg/commit/fd7b41984077464f19a059eacdd217170b1bcfa1
